# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a47a4961e2e3a020f644aa5e90f416b69e0c74a28a48efa9406ad66d4c9fb7b19daf1c6111682a3f2dc1089070283509bbe23c004947358086816a123f07bca

test:
  secret_key_base: bca4a9163a408e14b776af772a8c3d056026d5d0272f1922fe85bc4ed8909c22b93fff19de00e5392458500225bc8136090976a6a4b40c8bdc042be466965d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
